name: Tests

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/checkout@v4
    
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0'
          environment-name: ${{ matrix.python-version }}
          create-args: >-
            pip
            numpy
            python=${{ matrix.python-version }}
          post-cleanup: 'all'
      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install pytest
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Run custom command in micromamba environment
        run: pytest
        shell: micromamba-shell {0}